### ISSUE TITLE
You could add more 

### ISSUE THREAD

**Issue by ChisAdrian** [tgalaj/strutil#12]
before/after Last/First Cha
Example 
std::string beforeLastChar(const std::string& str, char target) {
    size_t lastPos = str.find_last_of(target);

    if (lastPos != std::string::npos) {
        return str.substr(0, lastPos);
    }

    return str; // Return the whole string if the character is not found
}

**Comment by tgalaj** [comment]
Thank you for your suggestion. Feel free to make a pull request out of it and please link this issue to the PR.
