### ISSUE TITLE
Allow other container types than std::vector where it makes sense

### ISSUE THREAD

**Issue by GustavLindberg99** [tgalaj/strutil#13]
I'm trying to use `join` on an std::set, but the function can only take an std::vector. [Your implementation](https://github.com/tgalaj/strutil/blob/master/strutil.h#L469) doesn't seem to do anything that can't be done with a set, so I suggest you make it a template so that it can take any container. Unless I'm missing something, it should work fine if you simply change the signature to

```c++
template<typename Container>
static inline std::string join(const Container & tokens, const std::string & delim)
```

Also you have some other functions that use std::vector where other containers would also work. Maybe you could go through them and see which ones could support other containers as well.

**Comment by tgalaj** [comment]
Thanks for the suggestion. I'm kind of reluctant to design the API this way, as we don't have the knowledge what type of data will be stored in a `Container` - this could be anything, but we specifically expect `std::string`. I'm not a template expert, but maybe there's a way to get to know what data type we expect to be in the `Container`. 

On the other hand, we could have a specialized functions for `std::set` (but this could lead to code duplication, I think some parts of the common code could be extracted to a separate functions). 

The other workaround could be to convert `std::set` to `std::vector` back and forth (but this may not be an option).

There are many possible solutions to this. I'd prefer to choose the simplest one. Feel free to propose a pull request on this.

**Comment by GustavLindberg99** [comment]
> Thanks for the suggestion. I'm kind of reluctant to design the API this way, as we don't have the knowledge what type of data will be stored in a `Container` - this could be anything, but we specifically expect `std::string`. I'm not a template expert, but maybe there's a way to get to know what data type we expect to be in the `Container`.

Do you mean like this?

```c++
template<template<class> class Container, typename T>
static inline std::string join(const Container<T> & tokens, const std::string & delim){
    //some code
}
```

This forces Container to be a template, and gives you access to T in the function body as you have now.

As an aside, your current implementation already allows the data stored in the vector to be anything that has an overloaded `<<` operator with `std::ostringstream`. In other parts of my code I take advantage of the fact that `int` fulfills this condition.

> On the other hand, we could have a specialized functions for `std::set` (but this could lead to code duplication, I think some parts of the common code could be extracted to a separate functions).

For `std::set` this would work, but as you say, it would lead to code duplication, and also it wouldn't allow other containers such as `std::list` or containers from third-party libraries. I currently only have a use case for `std::set`, but the advantage with a template is that other users can use it on any container they want.

> The other workaround could be to convert `std::set` to `std::vector` back and forth (but this may not be an option).

That's the workaround I'm currently using, but I would prefer being able to use it with `std::set` directly.

> There are many possible solutions to this. I'd prefer to choose the simplest one. Feel free to propose a pull request on this.

Ok, I did that here: https://github.com/tgalaj/strutil/pull/15. If you would like to do it a different way feel free to edit my pull request.

**Comment by tgalaj** [comment]
Thanks for the PR! I made some changes to it, so please review them in your spare time.

**Comment by GustavLindberg99** [comment]
It looks good to me. The only thing I'm wondering about is why you changed `strutil::drop_empty(tokens);` to `strutil::drop_empty<std::vector>(tokens);`. Does it not work anymore without the `<std::vector>`? If it doesn't, that doesn't seem very good to me. Also, why did you increment the major version instead of the minor version? Are there any breaking changes?

**Comment by tgalaj** [comment]
> It looks good to me. The only thing I'm wondering about is why you changed strutil::drop_empty(tokens); to strutil::drop_empty<std::vector>(tokens);. Does it not work anymore without the <std::vector>? If it doesn't, that doesn't seem very good to me

Yes, there were some compilation errors.

> Also, why did you increment the major version instead of the minor version? Are there any breaking changes?

Only the one you mentioned above - requiring to specify what type of container we use: `strutil::drop_empty<std::vector>(tokens);`.

**Comment by GustavLindberg99** [comment]
Are you sure? I tried building it without the `<std::vector>` and it worked for me. This is what I did, and it worked fine:

```bash
git clone https://github.com/GustavLindberg99/strutil
cd strutil
# Here I edited line 473 and 483 of tests/test_cases.cpp to remove the <std::vector>
cmake .
make
```

**Comment by tgalaj** [comment]
Probably depends on what compiler you use. VC and g++ (on github actions) both weren't able to compile and run the tests. I did some variadic template voodoo, and it now works without the need to specify the container type in the `<>`.

**Comment by GustavLindberg99** [comment]
That looks good to me. If I understand correctly it's no longer a breaking change though.
